# Generated by Django 3.1.3 on 2020-12-26 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sections', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name_section',
            field=models.CharField(max_length=20, unique=True, verbose_name='Name'),
        ),
    ]
