# Generated by Django 3.1.3 on 2020-12-26 20:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('CustomUsers', '0002_auto_20201226_2204'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='staff',
            new_name='is_staff',
        ),
    ]
